<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>72c38c2a-52f5-4a12-81d9-dc85c4d46481</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Stripe.net" Version="52.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartPharmacy.DAL\SmartPharmacy.DAL.csproj" />
  </ItemGroup>

</Project>
